services:
  - type: web
    name: enhanced-affiliate-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHANNEL_IDS
        sync: false
      - key: AFFILIATE_TAG
        value: budgetlooks08-21
      - key: ERROR_CHAT_ID
        sync: false
      - key: TINYURL_API_TOKEN
        sync: false
